plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - php
  phpcodesniffer:
    enabled: true
    config:
        standard: "PSR1,PSR2"
  sonar-php:
    enabled: true
    config:
      minimum_severity: critical
exclude_patterns:
  - config/
  - db/
  - dist/
  - features/
  - "**/node_modules/"
  - script/
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - Tests/
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/*.min.js"
  - "**/*.min.css"
  - "**/__tests__/"
  - "**/__mocks__/"
